sudo: required

services:
- docker

dist: trusty

env:
  global:
  - DOCKER_IMAGE=nimbostratuz/bikeshare-directions
  - IMAGE_VERSION=0.1

script:
- docker build -t "$DOCKER_IMAGE:$IMAGE_VERSION" .

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"

branches:
  only:
  - master
