env: dev
name: bikeshare-directions
version: 1.0.0

server:
  port: 8080
  baseurl: http://localhost:8080

config:
  etcd:
    url: http://localhost:2379

discovery:
  etcd:
    url: http://localhost:2379


maps:
  api:
    key: APIKEY1208402FADFASDF

foo: bar
